version: '3'

services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "8080:8080"
    environment:
      TIME_ADDITION_MS: 1000
      TIME_SUBTRACTION_MS: 1000
      TIME_MULTIPLICATION_MS: 1000
      TIME_DIVISION_MS: 1000

  agent:
    build: ./agent
    depends_on:
      - orchestrator

  grpc-server:
    build: ./grpc-server
    ports:
      - "50051:50051"
    depends_on:
      - orchestrator
